using HW2.Models;

namespace HW2.Services
{

    public class MessagingService
    {
        public List<Message> Messages;
        public int nextId = 100;
        
        public MessagingService()
        {
            Messages = new List<Message>
            {
                new Message { Id = 1, From = "Jim", To = "Al", Body = "Test messsage 1."},
                new Message { Id = 2, From = "John", To = "Joe", Body = "Message 1." }
            };
        }

        public List<Message> GetAll() => Messages;

        public void Add(Message message)
        {
            message.Id = nextId++; // Do not allow ID to be generated by anything but this class. 
            Messages.Add(message);
        }

    }
}